# Checkov configuration file
skip_check:
  # Skip sudo check for development container - sudo access is needed for developer workflow
  - CKV_DOCKER_9
  # Skip healthcheck check for interactive development container
  - CKV_DOCKER_2